"""empty message

Revision ID: 0e0d344c549e
Revises: a404c0877930
Create Date: 2020-07-16 11:28:21.644099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e0d344c549e'
down_revision = 'a404c0877930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reg_time', sa.DateTime(), nullable=True))
    op.drop_column('users', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('time', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'reg_time')
    # ### end Alembic commands ###
