"""empty message

Revision ID: a404c0877930
Revises: 46f56c365674
Create Date: 2020-07-13 17:03:59.115341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a404c0877930'
down_revision = '46f56c365674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jq_article_category',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=20), nullable=False),
    sa.Column('keywords', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cat_sort', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('dir', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('cat_id'),
    mysql_charset='utf8'
    )
    op.create_table('jq_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_jq_auth_add_time'), 'jq_auth', ['add_time'], unique=False)
    op.create_table('jq_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('comment_ip', sa.String(length=255), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_table('jq_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('auths', sa.String(length=600), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_jq_role_add_time'), 'jq_role', ['add_time'], unique=False)
    op.create_table('jq_tag',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.SmallInteger(), nullable=True),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tid'),
    mysql_charset='utf8'
    )
    op.create_table('jq_adminlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('operate', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_jq_adminlog_add_time'), 'jq_adminlog', ['add_time'], unique=False)
    op.create_table('jq_article',
    sa.Column('aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('shorttitle', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('keywords', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('allowcomments', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['cat_id'], ['jq_article_category.cat_id'], ),
    sa.PrimaryKeyConstraint('aid'),
    mysql_charset='utf8'
    )
    op.create_table('jq_oplog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=True),
    sa.Column('operate', sa.String(length=600), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_jq_oplog_add_time'), 'jq_oplog', ['add_time'], unique=False)
    op.create_table('article_tag',
    sa.Column('jq_article.aid', sa.Integer(), nullable=False),
    sa.Column('jq_tag.tid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jq_article.aid'], ['jq_article.aid'], ),
    sa.ForeignKeyConstraint(['jq_tag.tid'], ['jq_tag.tid'], ),
    sa.PrimaryKeyConstraint('jq_article.aid', 'jq_tag.tid')
    )
    op.add_column('users', sa.Column('is_super', sa.SmallInteger(), nullable=True))
    op.add_column('users', sa.Column('remarks', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('telephone', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users', 'jq_role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'time')
    op.drop_column('users', 'telephone')
    op.drop_column('users', 'status')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'remarks')
    op.drop_column('users', 'is_super')
    op.drop_table('article_tag')
    op.drop_index(op.f('ix_jq_oplog_add_time'), table_name='jq_oplog')
    op.drop_table('jq_oplog')
    op.drop_table('jq_article')
    op.drop_index(op.f('ix_jq_adminlog_add_time'), table_name='jq_adminlog')
    op.drop_table('jq_adminlog')
    op.drop_table('jq_tag')
    op.drop_index(op.f('ix_jq_role_add_time'), table_name='jq_role')
    op.drop_table('jq_role')
    op.drop_table('jq_comment')
    op.drop_index(op.f('ix_jq_auth_add_time'), table_name='jq_auth')
    op.drop_table('jq_auth')
    op.drop_table('jq_article_category')
    # ### end Alembic commands ###
