"""empty message

Revision ID: a71fc21bfead
Revises: 0e0d344c549e
Create Date: 2020-07-28 21:20:53.394806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71fc21bfead'
down_revision = '0e0d344c549e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jq_article', sa.Column('cat_name', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'jq_article', 'jq_article_category', ['cat_name'], ['cat_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jq_article', type_='foreignkey')
    op.drop_column('jq_article', 'cat_name')
    # ### end Alembic commands ###
