"""empty message

Revision ID: b541e69683c7
Revises: 0c81b9756334
Create Date: 2020-07-08 10:05:31.912896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b541e69683c7'
down_revision = '0c81b9756334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
